# action.yml
name: 'Journal of Digital History'
description: 'Add convenient tags to make your notebook shine'

inputs:
  notebook:
    description: 'relative path of your notebook ipynb file'
    required: true
    default: 'main.ipynb'
  output_notebook:
    required: false
    description: 'relative path where the skimmed notebook will be saved'

outputs:
  size:
    description: 'The number of total cells'
    value: ${{ steps.skim.outputs.size }}
  skimmed:
    description: 'The number of cells modified by this skim action'
    value: ${{ steps.skim.outputs.skimmed }}
  output_notebook:
    value: ${{ steps.skim.outputs.output_notebook }}

runs:
  using: 'composite'

  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.7'
    - name: Install Dependencies and run skim
      id: skim
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt
        python ${{ github.action_path }}/skim.py ${{ inputs.notebook }} ${{ inputs.output_notebook }}
      shell: bash
    - name: Display basic stats
      run: |
        echo "number of cells ${{ steps.skim.outputs.size }}"
        echo "skimmed ${{ steps.skim.outputs.skimmed }}"
      shell: bash
