# action.yml
name: 'Journal of Digital History'
description: 'Add convenient tags to make your notebook shine'
inputs:
  notebook:
    description: 'relative path of your notebook ipynb file'
    required: true
    default: 'main.ipynb'
outputs:
  size:
    description: 'The number of total cells'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.notebook }}
